### ISSUE TITLE
Wiki setup

### ISSUE THREAD

**Issue by Sacroxz** [Sacroxz/Todai#2]

**Comment by Sacroxz** [comment]
Initial structure proposal for the wiki:

### Resources for Users
- [Introduction](https://github.com/Sacroxz/Todai/wiki/Introduction) ― A brief overview of the app.
- [Installation](https://github.com/Sacroxz/Todai/wiki/Installation) ― Step-by-step instructions for installing Todai.
- [FAQ](https://github.com/Sacroxz/Todai/wiki/FAQ) ― Answers to frequently asked questions about the app.

### Resources for Developers
- [Getting Started](https://github.com/Sacroxz/Todai/wiki/Getting-Started) ― Step-by-step instructions for setting up the development environment.
- [Architecture](https://github.com/Sacroxz/Todai/wiki/Architecture) ― App architecture and design patterns.
- [Data Model](https://github.com/Sacroxz/Todai/wiki/Data-Model) ― Entities, attributes and database schema.
- [Contributing](https://github.com/Sacroxz/Todai/wiki/Contributing) ― Guidelines for developing Todai and submitting pull requests.

Thoughts, @Nanito111 ?

**Comment by Nanito111** [comment]
@Sacroxz It looks pretty good mate!
