### ISSUE TITLE
Project name change

### ISSUE THREAD

**Issue by Sacroxz** [Sacroxz/Todai#4]
Changing the project name from Todai to Toudai.

**Comment by Nanito111** [comment]
Github Project renamed!

**Comment by Sacroxz** [comment]
**Update:** Changed project name in README.md. [`619c121`](https://github.com/Sacroxz/Toudai/commit/619c1215b115bfb9c207fb4ccb0e5ceb02393aa6) [`0a41583`](https://github.com/Sacroxz/Toudai/commit/0a41583b28d02d8341948e9ee67b7d98220025f4)

**Comment by Sacroxz** [comment]
**Update**: Changed project name in wiki. [`c4ec8d`](https://github.com/Sacroxz/Toudai/wiki/Home/c4ec8db612e049e07131580c61f49390b89df542)

**Comment by Nanito111** [comment]
**Update**: Changed some missed old names in README.md [3afa27c](https://github.com/Sacroxz/Toudai/commit/3afa27c0fbbc509a58dcdb8de8f251bde25d4ba9)

**Comment by Sacroxz** [comment]
Everything seems fine now. For any future name changes we could just reopen this issue. Thoughts @Nanito111 ?

**Comment by Nanito111** [comment]
**Update**: I just renamed a missing one in License. [241b3f7](https://github.com/Sacroxz/Toudai/commit/241b3f70f8b07db68843c813f674887df7cbe9f5)

**Comment by Nanito111** [comment]
> Everything seems fine now. For any future name changes we could just reopen this issue. Thoughts @Nanito111 ?

I made a double check, so yeah, everything seems fine so I'm closing this issue. 🥂
